---
title: "Elo Adjusted Ranking"
author:
  - Stefan Stein
date: June 2022
output:
  html_document:
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, echo = TRUE)
```


```{r}
library(tidyverse)
library(igraph)
library(readxl)
```



Odds data

```{r}
dfm_2018 <- read_csv("data/Men 2018.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round == "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob) %>%
  mutate(logit_p_ij = log(p_ij / p_ji),
         lambda_w = 0.5*logit_p_ij,
         lambda_l = -0.5*logit_p_ij)

dfm_2019 <- read_csv("data/Men 2019.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round == "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob) %>%
  mutate(logit_p_ij = log(p_ij / p_ji),
         lambda_w = 0.5*logit_p_ij,
         lambda_l = -0.5*logit_p_ij)

dfm_2021 <- read_csv("data/Men 2021.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round == "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob) %>%
  mutate(logit_p_ij = log(p_ij / p_ji),
         lambda_w = 0.5*logit_p_ij,
         lambda_l = -0.5*logit_p_ij)


dfw_2018 <- read_csv("data/Women 2018.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round == "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob) %>%
  mutate(logit_p_ij = log(p_ij / p_ji),
         lambda_w = 0.5*logit_p_ij,
         lambda_l = -0.5*logit_p_ij)

dfw_2019 <- read_csv("data/Women 2019.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round == "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob) %>%
  mutate(logit_p_ij = log(p_ij / p_ji),
         lambda_w = 0.5*logit_p_ij,
         lambda_l = -0.5*logit_p_ij)

dfw_2021 <- read_csv("data/Women 2021.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round == "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob) %>%
  mutate(logit_p_ij = log(p_ij / p_ji),
         lambda_w = 0.5*logit_p_ij,
         lambda_l = -0.5*logit_p_ij)



```

Elo data

```{r, warning=FALSE}
atp18_myName <- read_excel("data/elo_ratings/atp18_myName.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text"))

atp19_myName <- read_excel("data/elo_ratings/atp2019_myname.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text"))

atp21_myName <- read_excel("data/elo_ratings/atp21_myname.xlsx", 
    col_types = c("numeric", "text", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text"))


wta18_myName <- read_excel("data/elo_ratings/wta18_myname.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text"))

wta19_myName <- read_excel("data/elo_ratings/wta19_myname.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text"))

wta21_myName <- read_excel("data/elo_ratings/wta21_myname.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text"))

```


Test data

```{r}
testm_2018 <- read_csv("data/wimbledon M 2018.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testm_2019 <- read_csv("data/wimbledon M 2019.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testm_2021 <- read_csv("data/wimbledon M 2021.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testw_2018 <- read_csv("data/wimbledon W 2018.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testw_2019 <- read_csv("data/wimbledon W 2019.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testw_2021 <- read_csv("data/wimbledon W 2021.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)
```


# Testing



```{r}
getLambda <- function(name, df){
  lambda <- df%>%
    filter(Player == name)%>%
    pull(lambda)
  if (length(lambda) == 0) {return(NA)}
  return(lambda)
}
```


```{r}
getLogLoss <- function(oddsData, eloData, testData){
  data <- oddsData%>%
    left_join(
      eloData%>%select(myName, Player, Elo), by = c("Winner" = "myName")
    )%>%
    rename("EloW" = "Elo", "PlayerW" = "Player")%>%
    left_join(
      eloData%>%select(myName, Player, Elo), by = c("Loser" = "myName")
    )%>%
    rename("EloL" = "Elo", "PlayerL" = "Player")%>%
    filter(!is.na(PlayerW) & !is.na(PlayerL))%>%
    mutate(d_ij = 0.5*(EloW + EloL)*log(10)/400,
           lambda_w_a = lambda_w + d_ij,
           lambda_l_a = lambda_l + d_ij)
  
  lambdas2018 <- data%>%select(PlayerW, lambda_w_a)%>%rename(Player = PlayerW, lambda = lambda_w_a)%>%
    rbind(data%>%select(PlayerL,lambda_l_a)%>%rename(Player = PlayerL, lambda = lambda_l_a))
  
  testData%>%
    left_join(
    eloData%>%select(myName, Player, Elo), by = c("Winner" = "myName")
  )%>%
  rename("EloW" = "Elo", "PlayerW" = "Player")%>%
  left_join(
    eloData%>%select(myName, Player, Elo), by = c("Loser" = "myName")
  )%>%
  rename("EloL" = "Elo", "PlayerL" = "Player")%>%
  filter(!is.na(PlayerW) & !is.na(PlayerL))%>%
  rowwise()%>%
  mutate(lambdaW = getLambda(PlayerW, lambdas2018),
         lambdaL = getLambda(PlayerL, lambdas2018))%>%
  filter(!is.na(lambdaW) & !is.na(lambdaL))%>%
  mutate(elo_p_winner = exp(lambdaW) / (exp(lambdaW) + exp(lambdaL)),
         marketLoss = -log(p_ij),
         eloLoss = -log(elo_p_winner))%>%
  ungroup()%>%
  summarise(marketLL = sum(marketLoss), eloLL = sum(eloLoss), n = nrow(.))
}
```

```{r}
results <- 
  bind_rows(
    getLogLoss(oddsData = dfm_2018, eloData = atp18_myName, testData = testm_2018)%>%mutate(gender = "M", year = "2018"),
    getLogLoss(oddsData = dfm_2019, eloData = atp19_myName, testData = testm_2019)%>%mutate(gender = "M", year = "2019"),
    getLogLoss(oddsData = dfm_2021, eloData = atp21_myName, testData = testm_2021)%>%mutate(gender = "M", year = "2021"),
    getLogLoss(oddsData = dfw_2018, eloData = wta18_myName, testData = testw_2018)%>%mutate(gender = "W", year = "2018"),
    getLogLoss(oddsData = dfw_2019, eloData = wta19_myName, testData = testw_2019)%>%mutate(gender = "W", year = "2019"),
    getLogLoss(oddsData = dfw_2021, eloData = wta21_myName, testData = testw_2021)%>%mutate(gender = "W", year = "2021")
  )

```

```{r}
results%>%
  mutate(elo_minus_market = eloLL - marketLL)%>%
  select(year, gender, n, marketLL, eloLL, elo_minus_market)
```
