---
title: "Elo Adjusted Ranking"
author:
  - Stefan Stein
date: June 2022
output:
  html_document:
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, echo = TRUE)
```


```{r message=FALSE}
library(tidyverse)
library(igraph)
library(readxl)
```



Odds data

```{r}
# Don't Repeat Yourself. :-)

transform_odds <- function(filename) {
  read_csv(filename,
           col_types = cols(Date = col_date(format = '%d/%m/%Y'))) %>%
    filter(Tournament == 'Wimbledon' & Round == '1st Round') %>%
    transmute(Winner, Loser, AvgW, AvgL,
              p_ij = 1 / AvgW,
              p_ji = 1 / AvgL,
              total_prob = p_ij + p_ji) %>%
    mutate(p_ij = p_ij / total_prob,
           p_ji = p_ji / total_prob) %>%
    select(-total_prob) %>%
    mutate(logit_p_ij = log(p_ij / p_ji),
           lambda_w = 0.5 * logit_p_ij,
           lambda_l = -lambda_w)
}

dfm_2018 <- transform_odds('data/Men 2018.csv')
dfm_2019 <- transform_odds('data/Men 2019.csv')
dfm_2021 <- transform_odds('data/Men 2021.csv')
dfw_2018 <- transform_odds('data/Women 2018.csv')
dfw_2019 <- transform_odds('data/Women 2019.csv')
dfw_2021 <- transform_odds('data/Women 2021.csv')
```

Elo data

```{r, warning=FALSE}
atp18_myName <- read_excel("data/elo_ratings/atp18_myName.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "numeric", 
        "text", "text", "text", "text"))

atp19_myName <- read_excel("data/elo_ratings/atp2019_myname.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "numeric", 
        "text", "text", "text", "text"))

atp21_myName <- read_excel("data/elo_ratings/atp21_myname.xlsx", 
    col_types = c("numeric", "text", "numeric", 
        "text", "text", "text", "text", "text", 
        "numeric", "text"))


wta18_myName <- read_excel("data/elo_ratings/wta18_myname.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "numeric", 
        "text", "text", "text", "text"))

wta19_myName <- read_excel("data/elo_ratings/wta19_myname.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "numeric", 
        "text", "text", "text", "text"))

wta21_myName <- read_excel("data/elo_ratings/wta21_myname.xlsx", 
    col_types = c("numeric", "text", "text", 
        "numeric", "text", "text", "text", 
        "text", "text", "numeric", "text"))

```


Test data

```{r}
testm_2018 <- read_csv("data/wimbledon M 2018.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testm_2019 <- read_csv("data/wimbledon M 2019.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testm_2021 <- read_csv("data/wimbledon M 2021.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testw_2018 <- read_csv("data/wimbledon W 2018.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testw_2019 <- read_csv("data/wimbledon W 2019.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)

testw_2021 <- read_csv("data/wimbledon W 2021.csv", col_types = cols(Date = col_date(format = "%d/%m/%Y")))%>%
  filter(Tournament == "Wimbledon" & Round != "1st Round")%>%
  select(Winner, Loser, AvgW, AvgL)%>%
  mutate(p_ij = 1 / AvgW,
         p_ji = 1/ AvgL,
         total_prob = p_ij + p_ji) %>%
  mutate(p_ij = p_ij / total_prob,
         p_ji = p_ji / total_prob) %>%
  select(-total_prob)
```


# Testing



```{r}
getLambda <- function(name, df){
  lambda <- df%>%
    filter(Player == name)%>%
    pull(lambda)
  if (length(lambda) == 0) {return(NA)}
  return(lambda)
}
```


```{r}
getLogLoss <- function(oddsData, eloData, testData, rankingType="Elo"){
  data <- oddsData%>%
    left_join(
      eloData%>%select(myName, Player, all_of(rankingType)), by = c("Winner" = "myName")
    )%>%
    rename("EloW" = rankingType, "PlayerW" = "Player")%>%
    left_join(
      eloData%>%select(myName, Player, all_of(rankingType)), by = c("Loser" = "myName")
    )%>%
    rename("EloL" = rankingType, "PlayerL" = "Player")%>%
    filter(!is.na(PlayerW) & !is.na(PlayerL))%>%
    mutate(d_ij = 0.5*(EloW + EloL)*log(10)/400,
           lambda_w_a = lambda_w + d_ij,
           lambda_l_a = lambda_l + d_ij)
  
  lambdas <- data%>%select(PlayerW, lambda_w_a)%>%rename(Player = PlayerW, lambda = lambda_w_a)%>%
    rbind(data%>%select(PlayerL,lambda_l_a)%>%rename(Player = PlayerL, lambda = lambda_l_a))
  
  testData%>%
    left_join(
    eloData%>%select(myName, Player, all_of(rankingType)), by = c("Winner" = "myName")
  )%>%
  rename("EloW" = rankingType, "PlayerW" = "Player")%>%
  left_join(
    eloData%>%select(myName, Player, all_of(rankingType)), by = c("Loser" = "myName")
  )%>%
  rename("EloL" = rankingType, "PlayerL" = "Player")%>%
  filter(!is.na(PlayerW) & !is.na(PlayerL))%>%
  rowwise()%>%
  mutate(lambdaW = getLambda(PlayerW, lambdas),
         lambdaL = getLambda(PlayerL, lambdas))%>%
  filter(!is.na(lambdaW) & !is.na(lambdaL))%>%
  mutate(elo_p_winner = exp(lambdaW) / (exp(lambdaW) + exp(lambdaL)),
         marketLoss = -log(p_ij),
         eloLoss = -log(elo_p_winner))%>%
  ungroup()%>%
  summarise(marketLL = sum(marketLoss), eloLL = sum(eloLoss), n = nrow(.))
}
```

```{r}
results <- 
  bind_rows(
    getLogLoss(oddsData = dfm_2018, eloData = atp18_myName, testData = testm_2018)%>%mutate(gender = "M", year = "2018"),
    getLogLoss(oddsData = dfm_2019, eloData = atp19_myName, testData = testm_2019)%>%mutate(gender = "M", year = "2019"),
    getLogLoss(oddsData = dfm_2021, eloData = atp21_myName, testData = testm_2021)%>%mutate(gender = "M", year = "2021"),
    getLogLoss(oddsData = dfw_2018, eloData = wta18_myName, testData = testw_2018)%>%mutate(gender = "W", year = "2018"),
    getLogLoss(oddsData = dfw_2019, eloData = wta19_myName, testData = testw_2019)%>%mutate(gender = "W", year = "2019"),
    getLogLoss(oddsData = dfw_2021, eloData = wta21_myName, testData = testw_2021)%>%mutate(gender = "W", year = "2021")
  )

```

```{r}
results%>%
  mutate(elo_minus_market = eloLL - marketLL)%>%
  select(year, gender, n, marketLL, eloLL, elo_minus_market)
```


```{r}
results_gElo <- 
  bind_rows(
    getLogLoss(oddsData = dfm_2018, eloData = atp18_myName, testData = testm_2018, rankingType = "Grass")%>%mutate(gender = "M", year = "2018"),
    getLogLoss(oddsData = dfm_2019, eloData = atp19_myName, testData = testm_2019, rankingType = "Grass")%>%mutate(gender = "M", year = "2019"),
    getLogLoss(oddsData = dfm_2021, eloData = atp21_myName, testData = testm_2021, rankingType = "gElo")%>%mutate(gender = "M", year = "2021"),
    getLogLoss(oddsData = dfw_2018, eloData = wta18_myName, testData = testw_2018, rankingType = "Grass")%>%mutate(gender = "W", year = "2018"),
    getLogLoss(oddsData = dfw_2019, eloData = wta19_myName, testData = testw_2019, rankingType = "Grass")%>%mutate(gender = "W", year = "2019"),
    getLogLoss(oddsData = dfw_2021, eloData = wta21_myName, testData = testw_2021, rankingType = "gElo")%>%mutate(gender = "W", year = "2021")
  )

```


```{r}
results_gElo%>%
  mutate(elo_minus_market = eloLL - marketLL)%>%
  select(year, gender, n, marketLL, eloLL, elo_minus_market)
```


# Optimize


```{r}
getLogLossFiller <- function(oddsData, eloData, testData, rankingType="Elo", filler=1200, return_full = FALSE){
  data <- oddsData%>%
    left_join(
      eloData%>%select(myName, Player, all_of(rankingType)), by = c("Winner" = "myName")
    )%>%
    rename("EloW" = rankingType, "PlayerW" = "Player")%>%
    left_join(
      eloData%>%select(myName, Player, all_of(rankingType)), by = c("Loser" = "myName")
    )%>%
    rename("EloL" = rankingType, "PlayerL" = "Player")%>%
    mutate(EloW = ifelse(is.na(EloW), filler, EloW),
           EloL = ifelse(is.na(EloL), filler, EloL))%>%
    mutate(d_ij = 0.5*(EloW + EloL)*log(10)/400,
           lambda_w_a = lambda_w + d_ij,
           lambda_l_a = lambda_l + d_ij)
  
  lambdas <- data%>%select(Winner, lambda_w_a)%>%rename(Player = Winner, lambda = lambda_w_a)%>%
    rbind(data%>%select(Loser,lambda_l_a)%>%rename(Player = Loser, lambda = lambda_l_a))
  
  test_restults <- testData%>%
    left_join(
      eloData%>%select(myName, Player, all_of(rankingType)), by = c("Winner" = "myName")
    )%>%
  rename("EloW" = rankingType, "PlayerW" = "Player")%>%
  left_join(
    eloData%>%select(myName, Player, all_of(rankingType)), by = c("Loser" = "myName")
  )%>%
  rename("EloL" = rankingType, "PlayerL" = "Player")%>%
  rowwise()%>%
  mutate(lambdaW = getLambda(Winner, lambdas),
         lambdaL = getLambda(Loser, lambdas))%>%
  mutate(elo_p_winner = exp(lambdaW) / (exp(lambdaW) + exp(lambdaL)),
         marketLoss = -log(p_ij),
         eloLoss = -log(elo_p_winner))%>%
  ungroup()%>%
  summarise(marketLL = sum(marketLoss), eloLL = sum(eloLoss), n = nrow(.))
  if (return_full) { return(test_restults)}
  return(test_restults%>%pull(eloLL))
}
```

```{r}
resultsFiller <- 
  bind_rows(
    getLogLossFiller(oddsData = dfm_2018, eloData = atp18_myName, testData = testm_2018, return_full = TRUE)%>%mutate(gender = "M", year = "2018"),
    getLogLossFiller(oddsData = dfm_2019, eloData = atp19_myName, testData = testm_2019, return_full = TRUE)%>%mutate(gender = "M", year = "2019"),
    getLogLossFiller(oddsData = dfm_2021, eloData = atp21_myName, testData = testm_2021, return_full = TRUE)%>%mutate(gender = "M", year = "2021"),
    getLogLossFiller(oddsData = dfw_2018, eloData = wta18_myName, testData = testw_2018, return_full = TRUE)%>%mutate(gender = "W", year = "2018"),
    getLogLossFiller(oddsData = dfw_2019, eloData = wta19_myName, testData = testw_2019, return_full = TRUE)%>%mutate(gender = "W", year = "2019"),
    getLogLossFiller(oddsData = dfw_2021, eloData = wta21_myName, testData = testw_2021, return_full = TRUE)%>%mutate(gender = "W", year = "2021")
  )

```



```{r}
results_filler%>%
  mutate(elo_minus_market = eloLL - marketLL)%>%
  select(year, gender, n, marketLL, eloLL, elo_minus_market)
```


```{r}
optim_2018 <- function(filler){
  getLogLossFiller(oddsData = dfm_2018, eloData = atp18_myName, testData = testm_2018, filler = filler)
}
optim_2019 <- function(filler){
  getLogLossFiller(oddsData = dfm_2019, eloData = atp19_myName, testData = testm_2019, filler = filler)
}
optim_2021 <- function(filler){
  getLogLossFiller(oddsData = dfm_2021, eloData = atp21_myName, testData = testm_2021, filler = filler)
}
```

```{r}
res2018 <- optimize(optim_2018,interval = c(1200, 2500))
res2019 <- optimize(optim_2019,interval = c(1200, 2500))
res2021 <- optimize(optim_2021,interval = c(1200, 2500))
```


```{r}
res2018
```

```{r}
res2019
```


```{r}
res2021
```


```{r}
optiw_2018 <- function(filler){
  getLogLossFiller(oddsData = dfw_2018, eloData = wta18_myName, testData = testw_2018, filler = filler)
}
optiw_2019 <- function(filler){
  getLogLossFiller(oddsData = dfw_2019, eloData = wta19_myName, testData = testw_2019, filler = filler)
}
optiw_2021 <- function(filler){
  getLogLossFiller(oddsData = dfw_2021, eloData = wta21_myName, testData = testw_2021, filler = filler)
}
```


```{r}
res2018W <- optimize(optiw_2018,interval = c(1200, 2500))
res2019W <- optimize(optiw_2019,interval = c(1200, 2500))
res2021W <- optimize(optiw_2021,interval = c(1200, 2500))
```

```{r}
res2018W
res2019W
res2021W
```




# Average Elo

```{r}
avg_elo <- function(oddsData, eloData){
  oddsData%>%
    left_join(
      eloData%>%select(myName, Player, all_of(rankingType)), by = c("Winner" = "myName")
    )%>%
    rename("EloW" = rankingType, "PlayerW" = "Player")%>%
    left_join(
      eloData%>%select(myName, Player, all_of(rankingType)), by = c("Loser" = "myName")
    )%>%
    rename("EloL" = rankingType, "PlayerL" = "Player")%>%
    summarise(mean_EloW = mean(EloW, na.rm = T),
              mean_EloL = mean(EloL, na.rm = T),
              mean_Elo = (mean_EloW + mean_EloL)/2)
}

```


```{r}
bind_rows(
  avg_elo(dfm_2018, atp18_myName)%>%mutate(gender="M", year=2018),
  avg_elo(dfm_2019, atp19_myName)%>%mutate(gender="M", year=2019),
  avg_elo(dfm_2021, atp21_myName)%>%mutate(gender="M", year=2021),
  avg_elo(dfw_2018, wta18_myName)%>%mutate(gender="W", year=2018),
  avg_elo(dfw_2019, wta19_myName)%>%mutate(gender="W", year=2019),
  avg_elo(dfw_2021, wta21_myName)%>%mutate(gender="W", year=2021)
)
```




